# docker-compose.yaml

version: "3"

services:
  mysql:
    image: mysql:5.7
    container_name: xx-mysql
    environment:
      MYSQL_ROOT_PASSWORD: zhangsan123
    ports:
      - "3306:3306"
    volumes:
    # 设置数据库默认的字符集
      - ./charset_and_collation.cnf:/etc/mysql/conf.d/my_custom.cnf
    # 数据挂载
      - ./mysql_data:/var/lib/mysql
    # 空白数据库会执行下面的sql脚本
      - ./xxx_database.sql:/docker-entrypoint-initdb.d/init-db.sql 
    restart: always
